### PR TITLE
New version of actix-web & actix-net

### PR DESCRIPTION
**Pull request by max-frai**
After upgrade actix-net to 0.2, current release does not compile:
```
error[E0308]: mismatched types
   --> src/actors/telegram_server/mod.rs:150:28
    |
150 |         self.server = Some(server.start());
    |                            ^^^^^^^^^^^^^^ expected struct `actix_net::server::Server`, found struct `actix_net::server::server::Server`
    |
    = note: expected type `actix::Addr<actix_net::server::Server>`
               found type `actix::Addr<actix_net::server::server::Server>`
```

Pull request updates all dependencies to latest version. This fixes compile error and also removes duplications when latest versions are used.

### CODE REVIEW

**Comment by jeizsm** [comment]
Hi, @max-frai. Thank you for pull request. Can you remove caret symbol it is unnecessary and not specify patch version of crates except actix-web, like it been before
